apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: dist-mnist-for-e2e-test
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: tensorflow
            image: asifraza/tf-dist-mnist-testing:latest
            resources:
              requests:
                cpu: 2
                memory: 1024Mi
          nodeSelector:
            kubernetes.io/hostname: asia-ceph-node
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: tensorflow
            image: asifraza/tf-dist-mnist-testing:latest
            resources:
              requests:
                cpu: 2
                memory: 1024Mi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - 203.250.170.1
                    - 203.250.170.2
