kind: Pod
apiVersion: v1
metadata:
  name: pvc-claim
spec:
  containers:
  - name: pvc-claim
    image: nginx
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "apt-get -y update && apt-get -y install git && cd /mnt && git clone https://github.com/MolSSI-Education/parallel-programming.git && exit 0 || exit 1"
    volumeMounts:
      - name: pvc
        mountPath: "/mnt"
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: asifclaim
