apiVersion: v1
kind: Pod
metadata: 
  name: claim-nginx
spec: 
  containers: 
    - name: claim-nginx
      image: nginx
      volumeMounts: 
        - name: nginx-pv
          mountPath: /mnt
  volumes: 
    - name: nginx-pv
      persistentVolumeClaim:
        claimName: asifclaim
