apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: kisti-mpi
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
           containers:
           - image: asifraza/test-pvc:latest
             imagePullPolicy: Always
             name: kisti-mpi
             command: ['sh', '-c', 'cd /mnt && git clone https://github.com/MolSSI-Education/parallel-programming.git && mpirun --allow-run-as-root -n 4 python /mnt/parallel-programming/examples/mpi4py/example3/final/example3.py']
             volumeMounts:
               - name: nginx-pv
                 mountPath: /mnt
           volumes:
             - name: nginx-pv
               persistentVolumeClaim:
                 claimName: asifclaim
    Worker:
      replicas: 4
      template:
        spec:
          containers:
          - image: asifraza/test-pvc:latest
            imagePullPolicy: Always
            name: kisti-mpi
            volumeMounts:
              - name: nginx-pv
                mountPath: /mnt
            resources:
              limits:
                cpu: 2
                memory: "2048Mi"
          volumes:
            - name: nginx-pv
              persistentVolumeClaim:
                claimName: asifclaim
