apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: tensorflow-benchmarks
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
           containers:
           - image: asifraza/tensorflow-benchmarks:latest
             name: tensorflow-benchmarks
             command:
             - mpirun
             - --allow-run-as-root
             - -n
             - "3"
             - /home/mpiuser/mpi
    Worker:
      replicas: 3
      template:
        spec:
          containers:
          - image: asifraza/tensorflow-benchmarks:latest
            name: tensorflow-benchmarks
            resources:
              limits:
                cpu: 2

