apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: myjobs
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
             kubernetes.io/mykey: myjobs
          labels:
             schedulingStrategy: tfjob
        spec:
          schedulerName: my-scheduler
          containers:
            - name: tensorflow
              image: asifraza/tf-dist-mnist-testing:latest # asifraza/tensorflow-testing:latest
              resources:
                limits:
                  cpu: 6
                  memory: 2048Mi
                  nvidia.com/gpu: 0
                #limits:
                #  cpu: 2
                #  memory: 1024Mi
                #  nvidia.com/gpu: 0
    Worker:
      replicas: 2 
      restartPolicy: Never
      template:
        metadata:
          annotations:
             kubernetes.io/mykey: myjobs
          labels:
             schedulingStrategy: tfjob
        spec:
          schedulerName: my-scheduler
          containers:
            - name: tensorflow
              image: asifraza/tf-dist-mnist-testing:latest  #asifraza/tensorflow-testing:latest
              resources:
                limits:
                  cpu: 6 
                  memory: 2048Mi
                  nvidia.com/gpu: 0


